/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCard: typeof import('./src/components/ui/cards/AppCard.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    BaseInput: typeof import('./src/components/ui/inputs/BaseInput.vue')['default']
    Combobox: typeof import('./src/components/ui/inputs/Combobox.vue')['default']
    ComboBox: typeof import('./src/components/ui/inputs/ComboBox.vue')['default']
    DialogConfirmBase: typeof import('./src/components/ui/dialog/DialogConfirmBase.vue')['default']
    InputField: typeof import('./src/components/ui/inputs/InputField.vue')['default']
    ManualAdd: typeof import('./src/components/ui/dialog/ManualAdd.vue')['default']
    ManuallyAdd: typeof import('./src/components/ui/dialog/ManuallyAdd.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
